/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.DiseaseCatalog.Disease;
import Business.DiseaseCatalog.DiseaseCatalog;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Varun
 */
public class AddNewPatient extends javax.swing.JPanel {

    /**
     * Creates new form AddNewPatient
     */
    private JPanel userProcessContainer;
    private DiseaseCatalog diseaseCatalog;
    private PatientDirectory patientDirectory;
    
    public AddNewPatient(JPanel userProcessContainer, PatientDirectory patientDirectory, DiseaseCatalog diseaseCatalog) {
        initComponents();
        
    this.userProcessContainer = userProcessContainer;
    this.diseaseCatalog = diseaseCatalog;
    this.patientDirectory = patientDirectory; 
    populateDiseaseComboBox();
    }
    
    private void populateDiseaseComboBox(){
        diseaseListJComboBox.removeAllItems();
        for(Disease disease : diseaseCatalog.getDiseaseList()){
            diseaseListJComboBox.addItem(disease);
    
    }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diseaseListJComboBox = new javax.swing.JComboBox();
        createPatientJButton = new javax.swing.JButton();
        patientAgeJSpinner = new javax.swing.JSpinner();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bloodGroupJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New Patient");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 590, 41));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Patient Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Patient Age:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Blood Group:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 40));

        diseaseListJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        diseaseListJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseListJComboBoxActionPerformed(evt);
            }
        });
        add(diseaseListJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 210, 40));

        createPatientJButton.setBackground(new java.awt.Color(153, 153, 153));
        createPatientJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createPatientJButton.setText("Create Patient");
        createPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientJButtonActionPerformed(evt);
            }
        });
        add(createPatientJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 190, 50));

        patientAgeJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        add(patientAgeJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 210, 40));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
        add(patientNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Disease:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 40));

        bloodGroupJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bloodGroupJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupJComboBoxActionPerformed(evt);
            }
        });
        add(bloodGroupJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void diseaseListJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseListJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseListJComboBoxActionPerformed

    private void createPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientJButtonActionPerformed
        // TODO add your handling code here:
        Patient  patient = patientDirectory.addNewPatient();
        patient.setName(patientNameJTextField.getText());
        patient.setAge((Integer)patientAgeJSpinner.getValue());
        patient.setDisease((Disease)diseaseListJComboBox.getSelectedItem());
        patient.setBloodGroup((String)bloodGroupJComboBox.getSelectedItem());
        JOptionPane.showMessageDialog(null,"Patient Added successfully");
    }//GEN-LAST:event_createPatientJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePatients managePatients = (ManagePatients) component;
        managePatients.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void bloodGroupJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox bloodGroupJComboBox;
    private javax.swing.JButton createPatientJButton;
    private javax.swing.JComboBox diseaseListJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner patientAgeJSpinner;
    private javax.swing.JTextField patientNameJTextField;
    // End of variables declaration//GEN-END:variables
}
