/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.Enterprise.HospitalEnterprise;
import Business.Network.StateNetwork;
import Business.EcoSystem;
import Business.OrderQueue.OrderRequest;
import Business.Organization.ClinicOrganization;
import Business.UserAccount.UserAccount;
import Business.VaccineCatalog.VaccineCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varun
 */
public class DoctorOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyOrdersJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    ClinicOrganization organization;
    HospitalEnterprise enterprise;
    StateNetwork network;
    VaccineCatalog vaccineCatalog;
    EcoSystem business;
    public DoctorOrdersJPanel(JPanel userProcessContainer,UserAccount account, 
            ClinicOrganization organization, HospitalEnterprise enterprise, 
            StateNetwork network, VaccineCatalog vaccineCatalog, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.vaccineCatalog = vaccineCatalog;
        this.business = business;
        populateOrderTable();

    }
    public void populateOrderTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (OrderRequest request : userAccount.getOrderQueue().getOrderRequestList()){
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = "1";//request.getSupplier().getSupplierName()== null ? null : request.getSupplier();
            row[2] = request.getQuantity();
            row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[4] = request.getStatus();
            row[5] = request.getRequestDate();
            row[6] = request.getResolveDate() == null ? null : request.getResolveDate();
                       
            model.addRow(row);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        refreshTestJButton = new javax.swing.JButton();
        requestNewOrderJButton = new javax.swing.JButton();
        acceptDeliveryJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        trackOrderJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("My Orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 780, 41));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine", "Supplier", "Quantity", "Receiver", "Status", "Request Date", "Resolve Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 91, 850, 144));

        refreshTestJButton.setBackground(new java.awt.Color(153, 153, 153));
        refreshTestJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        refreshTestJButton.setText("Refresh Table");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        requestNewOrderJButton.setBackground(new java.awt.Color(153, 153, 153));
        requestNewOrderJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        requestNewOrderJButton.setText("Request New Order");
        requestNewOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestNewOrderJButtonActionPerformed(evt);
            }
        });
        add(requestNewOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        acceptDeliveryJButton.setBackground(new java.awt.Color(153, 153, 153));
        acceptDeliveryJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        acceptDeliveryJButton.setText("Accept Delivery");
        acceptDeliveryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptDeliveryJButtonActionPerformed(evt);
            }
        });
        add(acceptDeliveryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 100, 40));

        trackOrderJButton.setBackground(new java.awt.Color(153, 153, 153));
        trackOrderJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        trackOrderJButton.setText("Track Order");
        trackOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackOrderJButtonActionPerformed(evt);
            }
        });
        add(trackOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateOrderTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void requestNewOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestNewOrderJButtonActionPerformed

        NewOrderJPanel requestNewOrderJPanel = new NewOrderJPanel(userProcessContainer, userAccount,organization, network,enterprise.getPatientDirectory(),vaccineCatalog, this.business);
        userProcessContainer.add("RequestNewOrderJPanel", requestNewOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_requestNewOrderJButtonActionPerformed

    private void acceptDeliveryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptDeliveryJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        OrderRequest request = (OrderRequest)workRequestJTable.getValueAt(selectedRow, 0);
        String status = request.getStatus();
        if (status.equals("Processed by Logistics, Out for Delivery")){
        request.setStatus("Delivered");
        request.getLastOrderRequest().setStatus("Delivered");
        request.setResolveDate();
        request.getModeOfTransport().setStatus("Available");
        //organization.getInventoryCatalog().addNewItem(request.getVaccine(),request.getQuantity());
        JOptionPane.showMessageDialog(null,"Your order has been delivered !");
        }
        
        
        else{
            JOptionPane.showMessageDialog(null,"This order is not out for delivery yet !");
        }
        
        
        
       
        
        
    }//GEN-LAST:event_acceptDeliveryJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void trackOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackOrderJButtonActionPerformed
        // TODO add your handling code here:
        
                int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row !");
            return;
        }

        OrderRequest request = (OrderRequest)workRequestJTable.getValueAt(selectedRow, 0);
        
        TrackMyOrdersJPanel trackOrderJPanel = new TrackMyOrdersJPanel(userProcessContainer, request);
        userProcessContainer.add("TrackOrderJPanel", trackOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
          
        
        

    }//GEN-LAST:event_trackOrderJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptDeliveryJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestNewOrderJButton;
    private javax.swing.JButton trackOrderJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
