/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.StateNetwork;
import Business.Organization.ClinicOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Varun
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    ClinicOrganization organization;
    HospitalEnterprise enterprise;
    StateNetwork network;
    EcoSystem business;
    
    public DoctorWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization,HospitalEnterprise enterprise,StateNetwork network,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (ClinicOrganization)organization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        myPatientsJButton = new javax.swing.JButton();
        myOrdersJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        myOrdersJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Doctor Work Area");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 580, 41));

        myPatientsJButton.setBackground(new java.awt.Color(153, 153, 153));
        myPatientsJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        myPatientsJButton.setText("My Patients");
        myPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPatientsJButtonActionPerformed(evt);
            }
        });
        add(myPatientsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 268, 46));

        myOrdersJButton.setBackground(new java.awt.Color(153, 153, 153));
        myOrdersJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        myOrdersJButton.setText("My Orders");
        myOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOrdersJButtonActionPerformed(evt);
            }
        });
        add(myOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 268, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        myOrdersJButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        myOrdersJButton1.setText("My Orders");
        myOrdersJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myOrdersJButton1ActionPerformed(evt);
            }
        });
        add(myOrdersJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 268, 46));
    }// </editor-fold>//GEN-END:initComponents

    private void myPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPatientsJButtonActionPerformed
        // TODO add your handling code here:
        ManagePatients managePatients = new ManagePatients(userProcessContainer,enterprise.getPatientDirectory(),business.getDiseaseCatalog());
        userProcessContainer.add("ManagePatients", managePatients);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myPatientsJButtonActionPerformed

    private void myOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOrdersJButtonActionPerformed
        // TODO add your handling code here:
        DoctorOrdersJPanel myOrdersJPanel = new DoctorOrdersJPanel(userProcessContainer, account, organization, enterprise, network, business.getVaccineCatalog(), business);
        userProcessContainer.add("MyOrdersJPanel", myOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_myOrdersJButtonActionPerformed

    private void myOrdersJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myOrdersJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myOrdersJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton myOrdersJButton;
    private javax.swing.JButton myOrdersJButton1;
    private javax.swing.JButton myPatientsJButton;
    // End of variables declaration//GEN-END:variables
}
