/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctor;


import Business.CoOrdinates.Coordinates;
import Business.DiseaseCatalog.Disease;
import Business.EcoSystem;
import Business.Enterprise.CDCEnterprise;
import Business.Network.StateNetwork;
import Business.OrderQueue.OrderRequest;
import Business.Organization.ClinicOrganization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import Business.VaccineCatalog.Blood;
import Business.VaccineCatalog.Vaccine;
import Business.VaccineCatalog.VaccineCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.GoogleMaps.MapBrowser;

/**
 *
 * @author Varun
 */
public class NewOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestNewOrderJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    ClinicOrganization organization;
    StateNetwork network;
    PatientDirectory patientDirectory;
    VaccineCatalog vaccineCatalog;
    
    Coordinates coordinates;
    public NewOrderJPanel(JPanel userProcessContainer, UserAccount userAccount,ClinicOrganization organization, StateNetwork network, PatientDirectory patientDirectory, VaccineCatalog vaccineCatalog, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.network = network;
        this.patientDirectory = patientDirectory;
        this.vaccineCatalog = vaccineCatalog;
        coordinates = new Coordinates();
        //loadSupplierComboBox();
        loadPatientComboBox();
    }
    
    /*public void loadSupplierComboBox(){
        for (SupplierEnterprise supplierEnterprise: network.getEnterpriseDirectory().getSupplierEnterprise()) {
            for(Supplier supplier: supplierEnterprise.getSupplierDirectory().getSupplierList()){
                if(supplier!= null){
                supplierListJComboBox.addItem(supplier);
                }
            }
        }
    }*/
    
    public void loadPatientComboBox(){
        patientListJComboBox.removeAllItems();
        for(Patient patient : patientDirectory.getPatientList()){
            if(patient!= null){
            patientListJComboBox.addItem(patient);
            }
    }
    
    
    }
    
    public void loadVaccineComboBox(Disease disease){
    vaccineListJComboBox.removeAllItems();
        for(Vaccine vaccine: vaccineCatalog.getVaccineList()){
    if(vaccine.getDiseaseProtectedAgainst().equals(disease)){
    vaccineListJComboBox.addItem(vaccine);
    }
    
    }
    vaccineListJComboBox.addItem("Blood pack Request");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vaccineListJComboBox = new javax.swing.JComboBox();
        placeOrderJButton = new javax.swing.JButton();
        quantityJSpinner = new javax.swing.JSpinner();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientListJComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        setLocationJButton = new javax.swing.JButton();
        presetLocationJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Request New Order");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 590, 41));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Vaccine:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Location:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 160, 40));

        vaccineListJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vaccineListJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineListJComboBoxActionPerformed(evt);
            }
        });
        add(vaccineListJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 210, 40));

        placeOrderJButton.setBackground(new java.awt.Color(153, 153, 153));
        placeOrderJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        placeOrderJButton.setText("Place Order");
        placeOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderJButtonActionPerformed(evt);
            }
        });
        add(placeOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 170, 40));

        quantityJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        add(quantityJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 210, 40));

        backJButton.setBackground(new java.awt.Color(255, 102, 102));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Patient:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 40));

        patientListJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientListJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientListJComboBoxActionPerformed(evt);
            }
        });
        add(patientListJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 210, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Quantity:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 160, 40));

        setLocationJButton.setBackground(new java.awt.Color(153, 153, 153));
        setLocationJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        setLocationJButton.setText("Set new location");
        setLocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLocationJButtonActionPerformed(evt);
            }
        });
        add(setLocationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 210, 40));

        presetLocationJButton.setBackground(new java.awt.Color(153, 153, 153));
        presetLocationJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        presetLocationJButton.setText("Preset Location");
        presetLocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presetLocationJButtonActionPerformed(evt);
            }
        });
        add(presetLocationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderJButtonActionPerformed
        // TODO add your handling code here:
        OrderRequest request = null;
        if(coordinates==null){
        JOptionPane.showMessageDialog(null,"Please set the coordinates");
        return;
        }
        for(CDCEnterprise enterprise: network.getEnterpriseDirectory().getCDCEnterprise()){
            request = enterprise.getOrderQueue().addOrderRequest();
        }
        if(vaccineListJComboBox.getSelectedItem()!="Blood pack Request"){
            request.setVaccine((Vaccine)vaccineListJComboBox.getSelectedItem());}
        
        else if(vaccineListJComboBox.getSelectedItem().toString().equals("Blood pack Request")){
            
            String bloodGroup = ((Patient)patientListJComboBox.getSelectedItem()).getBloodGroup();
            Disease disease = ((Patient)patientListJComboBox.getSelectedItem()).getDisease();
            Blood blood = new Blood(bloodGroup,disease);     
            request.setVaccine(blood);
                }
        else{return;}
        request.setDestinationCoordinates(coordinates);
        request.setQuantity((Integer)quantityJSpinner.getValue());
        request.setPatient((Patient)patientListJComboBox.getSelectedItem());
        request.setSender(userAccount);
        request.setStatus("Order Placed");
//        
//        OrderRequest nextRequest = new OrderRequest();
//        
//        nextRequest.setSender(userAccount);
//        nextRequest.setStatus("Order Placed");
//        request.assignOrderRequest(nextRequest);
        OrderRequest lastRequest = request.getLastOrderRequest();
            
        lastRequest.createAndGetNewOrderRequest().setSender(userAccount);
        lastRequest.createAndGetNewOrderRequest().setStatus("Order Placed");
        

        /*
        lastRequest.createAndGetNewOrderRequest().setSender(userAccount);
        lastRequest.createAndGetNewOrderRequest().setStatus("Order Placed");
        */
        JOptionPane.showMessageDialog(null,"Order placed successfully !");
        //Organization org = null;
        userAccount.getOrderQueue().getOrderRequestList().add(request);
    }//GEN-LAST:event_placeOrderJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorOrdersJPanel doctorOrdersJPanel = (DoctorOrdersJPanel) component;
        doctorOrdersJPanel.populateOrderTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void vaccineListJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineListJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineListJComboBoxActionPerformed

    private void patientListJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientListJComboBoxActionPerformed
        // TODO add your handling code here:
        if(patientListJComboBox.getSelectedItem() != null){
            Patient patient = (Patient)patientListJComboBox.getSelectedItem();
            Disease disease = patient.getDisease();
            loadVaccineComboBox(disease);
        }
    }//GEN-LAST:event_patientListJComboBoxActionPerformed

    private void setLocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLocationJButtonActionPerformed
        // TODO add your handling code here:
        MapBrowser mapBrowser = new MapBrowser(userProcessContainer, coordinates);
        userProcessContainer.add("MapBrowser", mapBrowser);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_setLocationJButtonActionPerformed

    private void presetLocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presetLocationJButtonActionPerformed
        // TODO add your handling code here:
        coordinates = organization.getCoordinates();
        
        
    }//GEN-LAST:event_presetLocationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox patientListJComboBox;
    private javax.swing.JButton placeOrderJButton;
    private javax.swing.JButton presetLocationJButton;
    private javax.swing.JSpinner quantityJSpinner;
    private javax.swing.JButton setLocationJButton;
    private javax.swing.JComboBox vaccineListJComboBox;
    // End of variables declaration//GEN-END:variables
}
