/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CDCManagerRole;

import Business.DiseaseCatalog.Disease;
import Business.DiseaseCatalog.DiseaseCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varun
 */
public class ManageDiseaseCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiseaseCatalogJPanel
     */
    JPanel userProcessContainer;
    DiseaseCatalog diseaseCatalog;
    
    public ManageDiseaseCatalogJPanel(JPanel userProcessContainer, DiseaseCatalog diseaseCatalog) {
        initComponents();
        this.diseaseCatalog = diseaseCatalog;
        this.userProcessContainer = userProcessContainer;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) diseaseCatalogJTable.getModel();
        
        model.setRowCount(0);
        
        int i = 0;
        for(Disease disease: diseaseCatalog.getDiseaseList()){
            Object[] row = new Object[2];
            row[0] = ++i;
            row[1] = disease;
            model.addRow(row);
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        diseaseCatalogJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addNewDiseaseJButton = new javax.swing.JButton();
        removeDiseaseJButton = new javax.swing.JButton();
        diseaseNameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diseaseCatalogJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No", "Disease Name"
            }
        ));
        jScrollPane1.setViewportView(diseaseCatalogJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 106, 670, 179));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Disease Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 70, 190, 30));

        addNewDiseaseJButton.setBackground(new java.awt.Color(153, 153, 153));
        addNewDiseaseJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addNewDiseaseJButton.setText("Add New Disease");
        addNewDiseaseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDiseaseJButtonActionPerformed(evt);
            }
        });
        add(addNewDiseaseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 210, 40));

        removeDiseaseJButton.setBackground(new java.awt.Color(153, 153, 153));
        removeDiseaseJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        removeDiseaseJButton.setText("Remove Disease");
        removeDiseaseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDiseaseJButtonActionPerformed(evt);
            }
        });
        add(removeDiseaseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, -1));
        add(diseaseNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 260, 40));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 110, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Disease Catalog ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 580, 41));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Add Disease:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addNewDiseaseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDiseaseJButtonActionPerformed
        // TODO add your handling code here:
        String diseaseName = diseaseNameJTextField.getText();
        diseaseCatalog.addNewDisease(diseaseName);
        populateTable();
        
    }//GEN-LAST:event_addNewDiseaseJButtonActionPerformed

    private void removeDiseaseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDiseaseJButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = diseaseCatalogJTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        Disease disease = (Disease) diseaseCatalogJTable.getValueAt(selectedRow, 1);
        diseaseCatalog.removeDisease(disease);
        populateTable();
        
    }//GEN-LAST:event_removeDiseaseJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewDiseaseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable diseaseCatalogJTable;
    private javax.swing.JTextField diseaseNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeDiseaseJButton;
    // End of variables declaration//GEN-END:variables
}
