/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InventoryManager;

import Business.EcoSystem;
import Business.Enterprise.DistributorEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.InventoryManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Varun
 */
public class DistributorInventoryManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorInventoryManagerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    InventoryManagementOrganization organization;
    DistributorEnterprise enterprise;
    StateNetwork network;
    CountryNetwork countryNetwork;
    EcoSystem business;
    
    public DistributorInventoryManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,
            DistributorEnterprise enterprise,StateNetwork network, CountryNetwork countryNetwork, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (InventoryManagementOrganization)organization;
        this.enterprise = enterprise;
        this.network = network;
        this.countryNetwork = countryNetwork;
        this.business =business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        viewInventoryJButton = new javax.swing.JButton();
        processOrderRequestsJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Distributor Work Area");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 580, 41));

        viewInventoryJButton.setBackground(new java.awt.Color(153, 153, 153));
        viewInventoryJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewInventoryJButton.setText("View Inventory");
        viewInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInventoryJButtonActionPerformed(evt);
            }
        });
        add(viewInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 268, 46));

        processOrderRequestsJButton.setBackground(new java.awt.Color(153, 153, 153));
        processOrderRequestsJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        processOrderRequestsJButton.setText("Process Order Requests");
        processOrderRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processOrderRequestsJButtonActionPerformed(evt);
            }
        });
        add(processOrderRequestsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 290, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInventoryJButtonActionPerformed
        // TODO add your handling code here:
        ViewDistributorInventoryJPanel viewDistributorInventoryJPanel = new ViewDistributorInventoryJPanel(userProcessContainer, account, organization.getInventoryCatalog(), organization,business.getSupplierEnterprisesFromAllCountries(), network, countryNetwork,this.business);
        userProcessContainer.add("ViewDistributorInventoryJPanel", viewDistributorInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewInventoryJButtonActionPerformed

    private void processOrderRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processOrderRequestsJButtonActionPerformed
        // TODO add your handling code here:
        ProcessDistributorOrdersJPanel processDistributorOrdersJPanel = new ProcessDistributorOrdersJPanel(userProcessContainer,account, organization, enterprise, network, business.getAllDistributorEnterpriseOrderRequestFromAllCountries());
        userProcessContainer.add("ProcessDistributorOrdersJPanel", processDistributorOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processOrderRequestsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton processOrderRequestsJButton;
    private javax.swing.JButton viewInventoryJButton;
    // End of variables declaration//GEN-END:variables
}
