/*
 * To  change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GoogleMaps;

import Business.CoOrdinates.Coordinates;
import Business.Organization.Organization;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JPanel;


/**
 *
 * @author Varun
 */
public class MapBrowser extends javax.swing.JPanel {

    /**
     * Creates new form MapBrowser
     */
    final Browser browser;
    BrowserView browserView;
    JPanel userProcessContainer;
    Organization organization;
    Coordinates coordinates;
       
    
    public MapBrowser() {
        initComponents();
        //this.userProcessContainer = userProcessContainer;
        browser = new Browser();
        browserView = new BrowserView(browser);
        backJButton.setVisible(false);
        setMyLocationJButton.setVisible(false);
        loadThisBrowser();
    }
    
    public MapBrowser(JPanel userProcessContainer, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        browser = new Browser();
        browserView = new BrowserView(browser);
        backJButton.setVisible(true);
        setMyLocationJButton.setVisible(true);
        loadThisBrowser();
    }
    
    public MapBrowser(JPanel userProcessContainer, Coordinates coordinates) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.coordinates = coordinates;
        browser = new Browser();
        browserView = new BrowserView(browser);
        backJButton.setVisible(true);
        setMyLocationJButton.setVisible(true);
        loadThisBrowser();
    }
    
    
    public void loadThisBrowser(){
        
       mapsjPanel.add(browserView, BorderLayout.CENTER);
       browser.loadURL("https://www.google.com//maps");
        System.out.println("Printing");
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        btnjPanel = new javax.swing.JPanel();
        getUrlJButton = new javax.swing.JButton();
        setMyLocationJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        mapsjPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        btnjPanel.setBackground(new java.awt.Color(153, 255, 204));
        btnjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getUrlJButton.setBackground(new java.awt.Color(153, 153, 153));
        getUrlJButton.setText("Get URL");
        getUrlJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUrlJButtonActionPerformed(evt);
            }
        });
        btnjPanel.add(getUrlJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, 109, -1));

        setMyLocationJButton.setBackground(new java.awt.Color(153, 153, 153));
        setMyLocationJButton.setText("Set my location");
        setMyLocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMyLocationJButtonActionPerformed(evt);
            }
        });
        btnjPanel.add(setMyLocationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, 109, -1));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        btnjPanel.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 40));

        jSplitPane1.setLeftComponent(btnjPanel);

        mapsjPanel.setBackground(new java.awt.Color(153, 255, 204));
        mapsjPanel.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(mapsjPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void getUrlJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUrlJButtonActionPerformed
        // TODO add your handling code here:
        String url = browser.getURL();
        System.out.println("URL:"+url);
        
        // String to be scanned to find the pattern.
      
      String latitudePattern = "\\w+([0-9])+\\.([0-9])+\\w";
      
      String longitudePattern = "[^(\\,+\\@+\\w)]+([0-9])+\\.([0-9])+\\w";

      // Create a Pattern object
      Pattern lat = Pattern.compile(latitudePattern);
      Pattern lon = Pattern.compile(longitudePattern);

      // Now create matcher object.
      Matcher m = lat.matcher(url);
      Matcher n = lon.matcher(url);
      if (m.find( )&&n.find()) {
         System.out.println("Latitude: "+m.group());
         System.out.println("Longitude: "+n.group());
            try {
                calculateDistance();
                //System.out.println("Found value: " + m.group(1) );
                //System.out.println("Found value: " + m.group(2) );
            } catch (Exception ex) {
                Logger.getLogger(MapBrowser.class.getName()).log(Level.SEVERE, null, ex);
            }
      }else {
         System.out.println("NO MATCH");
      }
        
        
        
    }//GEN-LAST:event_getUrlJButtonActionPerformed

    private void setMyLocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMyLocationJButtonActionPerformed
        // TODO add your handling code here:
        
        String url = browser.getURL();
        // String to be scanned to find the pattern.
      
      String latitudePattern = "\\w+([0-9])+\\.([0-9])+\\w";
      
      String longitudePattern = "[^(\\,+\\@+\\w)]+([0-9])+\\.([0-9])+\\w";

      // Create a Pattern object
      Pattern lat = Pattern.compile(latitudePattern);
      Pattern lon = Pattern.compile(longitudePattern);

      // Now create matcher object.
      Matcher m = lat.matcher(url);
      Matcher n = lon.matcher(url);
      if (m.find( )&&n.find()) {
         System.out.println("Latitude: "+m.group());
         System.out.println("Longitude: "+n.group());
            try {
                calculateDistance();
                //System.out.println("Found value: " + m.group(1) );
                //System.out.println("Found value: " + m.group(2) );
            } catch (Exception ex) {
                Logger.getLogger(MapBrowser.class.getName()).log(Level.SEVERE, null, ex);
            }
      }else {
         System.out.println("NO MATCH");
      }
        
        
        if(organization!=null){
            Coordinates coordinates1 = new Coordinates();
            coordinates1.setCoordinates(m.group(), n.group());
            organization.setCoordinates(coordinates1);
        }
        else if(coordinates!=null){
        coordinates.setCoordinates(m.group(), n.group());
        }
    }//GEN-LAST:event_setMyLocationJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    public void calculateDistance( ) throws Exception{
    String key ="AIzaSyAyiHM8SthFspcIXSblPCok9ee42wjxQms"; 
    String urlString = "https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=40.6655101,-73.8918896&destinations=40.6905615%2C-73.9976592%7C40.659569%2C-73.933783%7C40.729029%2C-73.851524%7C40.6860072%2C-73.6334271%7C40.598566%2C-73.7527626%7C40.659569%2C-73.933783%7C40.729029%2C-73.851524%7C40.6860072%2C-73.6334271%7C40.598566%2C-73.7527626&key="+key;
    
    URL url = new URL(urlString);
        //URLConnection urlconn = url.openConnection();
        InputStreamReader in = null;
        StringBuilder sb = new StringBuilder();
        HttpURLConnection urlConn = (HttpURLConnection)url.openConnection();
        urlConn.setRequestMethod("GET");
        urlConn.connect();
//        urlconn.connect();
//        InputStream inputStream = urlconn.getInputStream();
         //= url.openStream();
        //System.out.println("Code: "+urlConn.getResponseCode());
        if (urlConn != null && urlConn.getInputStream() != null) {
				in = new InputStreamReader(urlConn.getInputStream(),
						Charset.defaultCharset());
				BufferedReader bufferedReader = new BufferedReader(in);
				if (bufferedReader != null) {
					int cp;
					while ((cp = bufferedReader.read()) != -1) {
						sb.append((char) cp);
					}
					bufferedReader.close();
				}
			}
		in.close();
                System.out.println(sb.toString()); 
                
     
               
JsonParser parser = new JsonParser(); 

JsonObject json = (JsonObject) parser.parse(sb.toString());

        JsonArray rows = json.getAsJsonArray("rows");
        
        Iterator <JsonElement> iterator1 = rows.iterator();
         
    while (iterator1.hasNext()) {
        
        Object obj = iterator1.next();
        if(obj instanceof JsonObject) {
           JsonArray elements = ((JsonObject)obj).getAsJsonArray("elements"); 
        
           
         Iterator <JsonElement> iterator2 = elements.iterator();
         int i =0;
    while (iterator2.hasNext()) {
        i++;
        JsonObject obj1 = (JsonObject)iterator2.next();
        if(obj1 instanceof JsonObject) {
            //JsonObject jsonObject = obj1.get("distance").getAsJsonObject();
            //System.out.println(jsonObject.get("text"));
            String dist = obj1.getAsJsonObject("distance").get("text").getAsString();
            String duration = obj1.getAsJsonObject("duration").get("text").getAsString();
            System.out.println("\n Element: "+ i+ "\t"+" Distance: "+dist+"\t Duration: "+duration);
        
        }
    }
           
        }
    }
        
        
        
        }        
        //System.out.println(distance);


/* 
* For distance, below is only partial solution as the 
* output to string destination_addr will contain square brackets [] and double codes ""
* Eg. [ "1600 Pennsylvania Avenue, Hagerstown, MD 21742, USA" ]
*/
/*
String destination_addr = json.get("destination_addresses").get("")
                            .toString();

StringBuilder stringBuilderDestinationAddr = new StringBuilder();

for (int i = 0; i < destination_addr.length(); i++)
    if (destination_addr.charAt(i) != '[' && destination_addr.charAt(i) != ']' && destination_addr.charAt(i) != '"')
         stringBuilderDestinationAddr.append(destination_addr.charAt(i));

String strCleanDestination = stringBuilderDestinationAddr.toString();
        System.out.println(strCleanDestination);
   
   
    
    }
  */   
    public void getCleanedDistances(){
    
//    //httpResponse is the output of google api
//JsonObject jsonRespRouteDistance = new JsonObject().getAsJsonObject(TOOL_TIP_TEXT_KEY)
//
//String distance = jsonRespRouteDistance.get("text").toString();
//
///* 
//* For distance, below is only partial solution as the 
//* output to string destination_addr will contain square brackets [] and double codes ""
//* Eg. [ "1600 Pennsylvania Avenue, Hagerstown, MD 21742, USA" ]
//* 
//*/
//String destination_addr = new JsonObject()
//                            .get("destination_addresses")
//                            .toString();
//
//StringBuilder stringBuilderDestinationAddr = new StringBuilder();
//
//for (int i = 0; i < destination_addr.length(); i++)
//    if (destination_addr.charAt(i) != '[' && destination_addr.charAt(i) != ']' && destination_addr.charAt(i) != '"')
//         stringBuilderDestinationAddr.append(pickup_addr.destination_addr (i));
//
//String strCleanDestination = stringBuilderDestinationAddr.toString();
//    
   }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel btnjPanel;
    private javax.swing.JButton getUrlJButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mapsjPanel;
    private javax.swing.JButton setMyLocationJButton;
    // End of variables declaration//GEN-END:variables
}
