/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateHealthDeptManager;

import Business.InventoryCatalog.InventoryItem;
import Business.Organization.SupplierOrganization;
import Business.SupplierDirectory.Supplier;
import Business.SupplierDirectory.VaccineStock;
import Business.UserAccount.UserAccount;
import Business.VaccineCatalog.Vaccine;
import Business.VaccineCatalog.VaccineCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Varun
 */
public class AddInventoryItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddInventoryItemJPanel
     */
    JPanel userProcessContainer;
    VaccineCatalog vaccineCatalog;
    SupplierOrganization supplierOrganization;
    UserAccount userAccount;
    public AddInventoryItemJPanel(JPanel userProcessContainer,UserAccount userAccount, VaccineCatalog vaccineCatalog, SupplierOrganization supplierOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vaccineCatalog = vaccineCatalog;
        this.userAccount = userAccount;
        this.supplierOrganization = supplierOrganization;
        this.populateVaccineComboBox();
    }
    
    public void populateVaccineComboBox(){
        vaccineJComboBox.removeAllItems();
        if(vaccineCatalog != null){
            for(Vaccine vaccine:vaccineCatalog.getVaccineList()) {
                vaccineJComboBox.addItem(vaccine);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        quantityJSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vaccineJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Quantity Available:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 40));

        saveJButton.setBackground(new java.awt.Color(153, 153, 153));
        saveJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        saveJButton.setText("Add Item");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 210, -1));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 110, 50));

        quantityJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        add(quantityJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Inventory Item");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 580, 41));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Vaccine Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 40));

        vaccineJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(vaccineJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 146, 200, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        if(quantityJSpinner.getValue().toString().matches("[A-Za-z]+")){
            JOptionPane.showMessageDialog(null, "Please enter valid quantity.");
            return;
        }
        int qty = (int)quantityJSpinner.getValue();
        Vaccine vaccine = (Vaccine) vaccineJComboBox.getSelectedItem();
        if(qty <= 0){
            JOptionPane.showMessageDialog(null, "Please enter valid quantity.");
            return;
        }
        InventoryItem v1 = this.supplierOrganization.getVaccineStock().getInventoryByVaccine(vaccine);
        if(v1 == null)
            this.supplierOrganization.addStock(vaccine, qty);
        else
            v1.setQuantity(v1.getQuantity() + qty);
        JOptionPane.showMessageDialog(null,"Inventory Item has been added successfully !");
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageSupplierInventoryJPanel manageSupplierInventoryJPanel = (ManageSupplierInventoryJPanel) component;
        manageSupplierInventoryJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner quantityJSpinner;
    private javax.swing.JButton saveJButton;
    private javax.swing.JComboBox vaccineJComboBox;
    // End of variables declaration//GEN-END:variables
}
