/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateHealthDeptManager;

import Business.SupplierDirectory.VaccineStock;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Varun
 */
public class EditInventoryItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditInventoryItemJPanel
     */
    JPanel userProcessContainer;
    VaccineStock vaccineStock;
    public EditInventoryItemJPanel(JPanel userProcessContainer,VaccineStock vaccineStock) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vaccineStock = vaccineStock;
        vaccineNameJLabel.setText(vaccineStock.toString());
        quantityJSpinner.setValue(vaccineStock.getQuantity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        vaccineNameJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        quantityJSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edit Inventory Item");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 580, 41));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Vaccine Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 105, 170, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Quantity Available:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, 50));

        saveJButton.setBackground(new java.awt.Color(153, 153, 153));
        saveJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });
        add(saveJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 150, 60));

        vaccineNameJLabel.setText("<Vaccine Name>");
        add(vaccineNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 230, 50));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 110, 50));

        quantityJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        add(quantityJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 220, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        vaccineStock.setQuantity((int) quantityJSpinner.getValue());
        JOptionPane.showMessageDialog(null,"Inventory Item has been modified successfully !");
       
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageSupplierInventoryJPanel manageSupplierInventoryJPanel = (ManageSupplierInventoryJPanel) component;
        manageSupplierInventoryJPanel.populateTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner quantityJSpinner;
    private javax.swing.JButton saveJButton;
    private javax.swing.JLabel vaccineNameJLabel;
    // End of variables declaration//GEN-END:variables
}
