/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateHealthDeptManager;

import Business.Enterprise.SupplierEnterprise;
import Business.InventoryCatalog.InventoryItem;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.VaccineCatalog.VaccineCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varun
 */
public class ManageSupplierInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSuppliersJPanel
     */
    JPanel userProcessContainer;
    VaccineCatalog vaccineCatalog;
    SupplierOrganization supplierOrganization;
    SupplierEnterprise supplierEnterprise;
    UserAccount userAccount;
    public ManageSupplierInventoryJPanel(JPanel userProcessContainer, UserAccount userAccount, VaccineCatalog vaccineCatalog, SupplierOrganization supplierOrganization, SupplierEnterprise supplierEnterprise) {
        initComponents();
        this. userProcessContainer = userProcessContainer;
        this.vaccineCatalog = vaccineCatalog;
        this.supplierOrganization = supplierOrganization;
        this.supplierEnterprise = supplierEnterprise;
        this.userAccount = userAccount;
        System.out.println("Print Out:");
        System.out.println(this.supplierOrganization.getVaccineStocksAvailable());
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) supplierInventoryJTable.getModel();
        model.setRowCount(0);
        int i=0;
        for (InventoryItem inventoryItem: this.supplierOrganization.getVaccineStocksAvailable()){
            Object[] row = new Object[3];
            row[0] = ++i;
            row[1] = inventoryItem;
            row[2] = inventoryItem.getQuantity();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        supplierInventoryJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        addInventoryItemJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierInventoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl No", "Vaccine Name"
            }
        ));
        jScrollPane1.setViewportView(supplierInventoryJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 600, 196));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Supplier Inventory");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 580, 41));

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/click-go-back-button.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 110, 50));

        addInventoryItemJButton.setBackground(new java.awt.Color(153, 153, 153));
        addInventoryItemJButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addInventoryItemJButton.setText("Add Item");
        addInventoryItemJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInventoryItemJButtonActionPerformed(evt);
            }
        });
        add(addInventoryItemJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 200, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/together-logo.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addInventoryItemJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInventoryItemJButtonActionPerformed
        AddInventoryItemJPanel addInventoryItemJPanel = new AddInventoryItemJPanel(userProcessContainer,userAccount, vaccineCatalog, this.supplierOrganization);
        userProcessContainer.add("AddInventoryItemJPanel", addInventoryItemJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addInventoryItemJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInventoryItemJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable supplierInventoryJTable;
    // End of variables declaration//GEN-END:variables
}
