/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.EcoSystem;
import Business.Enterprise.TravelAgencyEnterprise;
import Business.OrderQueue.OrderRequest;
import Business.Organization.LogisticsOrganization;
import Business.Organization.Organization;
import Business.Transport.ModeOfTransport;
import Business.Transport.ModeOfTransport.Type;
import Business.Transport.TransportDirectory;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class count_of_amb extends javax.swing.JPanel {

    /**
     * Creates new form count_of_amb
     */
    EcoSystem business;
    public count_of_amb(EcoSystem business) {
        initComponents();
        this.business = business;
        updateTable();
    }

    public void updateTable(){
        
        DefaultTableModel model = (DefaultTableModel)number_of_times_usedjTable.getModel();
        int drone = 0;
        int ambulance = 0;
        for(TravelAgencyEnterprise travelAgency : business.getAllTravelAgencyEnterprisesFromAllCountries()) {
            
            for( OrderRequest orderRequest:travelAgency.getOrderQueue().getOrderRequestList() ){
                if(orderRequest.getModeOfTransport().equals(ModeOfTransport.test.Drone)){
                    drone += 1;
                }
                else{
                    ambulance +=1;
                }
            }
        }
        Object[] row1 = new Object[2];
        row1[0] = "Drone";
        row1[1] = drone;
        model.addRow(row1);
        Object[] row2 = new Object[2];
        row2[0] = "Ambulance";
        row2[1] = ambulance;
        model.addRow(row2);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        number_of_times_usedjTable = new javax.swing.JTable();

        jLabel1.setText("Number of times Ambulance/Drones used");

        number_of_times_usedjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mode of transport", "Number of times used"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(number_of_times_usedjTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable number_of_times_usedjTable;
    // End of variables declaration//GEN-END:variables
}
