/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.Enterprise.HospitalEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.ClinicOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class Max_Doc_Req extends javax.swing.JPanel {

    /**
     * Creates new form Max_Doc_Req
     */
    CountryNetwork countryNetwork;
    JPanel userProcessContainer;
    public Max_Doc_Req(JPanel userProcessContainer,CountryNetwork countryNetwork ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.countryNetwork = countryNetwork;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)max_doc_req_jTable.getModel();
        
        model.setRowCount(0);
        
        for(StateNetwork stateNetwork : countryNetwork.getStateNetwork()){
        if(stateNetwork.getEnterpriseDirectory()!=null){
        for(HospitalEnterprise hospitalEnterprise: stateNetwork.getEnterpriseDirectory().getHospitalEnterprise()){
        if(hospitalEnterprise.getOrganizationDirectory()!=null){
        for(Organization organization: hospitalEnterprise.getOrganizationDirectory().getOrganizationList()){
        if(organization.getUserAccountDirectory()!=null){
        for(UserAccount userAccount: organization.getUserAccountDirectory().getUserAccountList()){
        
            Object[] row = new Object[3];
            row[0] = stateNetwork.getName();
            row[1] = userAccount.getEmployee().getName();
            row[2] = userAccount.getOrderQueue().getOrderRequestList().size();
            

            
            model.addRow(row);
        }
        }
        }
        }
        
        }
        
        }
        
        }
        
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        max_doc_req_jTable = new javax.swing.JTable();

        jLabel1.setText("Which Doctor got the maximum requests?");

        max_doc_req_jTable.setAutoCreateRowSorter(true);
        max_doc_req_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "State", "Doctor Name", "Number Of Requests"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(max_doc_req_jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable max_doc_req_jTable;
    // End of variables declaration//GEN-END:variables
}
