/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.OrderQueue.OrderRequest;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class Request_tracking_Analytics extends javax.swing.JPanel {

    /**
     * Creates new form Request_tracking_Analytics
     */
    
    JPanel userProcessContainer;
    EcoSystem business;
    public Request_tracking_Analytics(JPanel userProcessContainer,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    
    public void populateTable(){
    DefaultTableModel model = (DefaultTableModel)RequestTrackingjTable.getModel();
        
        model.setRowCount(0);int i=0;
        for(CountryNetwork countryNetwork : business.getCountryList()){
            if(countryNetwork.getStateNetwork()!=null){
        for(StateNetwork stateNetwork : countryNetwork.getStateNetwork()){
        if(stateNetwork.getEnterpriseDirectory()!=null){
        for(HospitalEnterprise hospitalEnterprise: stateNetwork.getEnterpriseDirectory().getHospitalEnterprise()){
        if(hospitalEnterprise.getOrganizationDirectory()!=null){
        for(Organization organization: hospitalEnterprise.getOrganizationDirectory().getOrganizationList()){
        if(organization.getUserAccountDirectory()!=null){
        for(UserAccount userAccount: organization.getUserAccountDirectory().getUserAccountList()){
        for(OrderRequest orderRequest : userAccount.getOrderQueue().getOrderRequestList()){
            Object[] row = new Object[7];
            row[0] = ++i;
            row[1] = countryNetwork.getName();
            row[2] = stateNetwork.getName();
            row[3] = orderRequest.getDestinationCoordinates().getLatitude();
            row[4] = orderRequest.getDestinationCoordinates().getLongitude();
            row[5] = orderRequest.getPatient().getDisease();
            row[6] = orderRequest.getVaccine().getName();

            
            model.addRow(row);}
        }
        }
        }
        }
        
        }
        }
        }
        }
        }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestTrackingjTable = new javax.swing.JTable();

        jLabel1.setText("Request Tracking Analytics");

        RequestTrackingjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Country", "State", "Latitude", "Longitude", "Disease", "Vaccine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RequestTrackingjTable);
        if (RequestTrackingjTable.getColumnModel().getColumnCount() > 0) {
            RequestTrackingjTable.getColumnModel().getColumn(0).setResizable(false);
            RequestTrackingjTable.getColumnModel().getColumn(1).setResizable(false);
            RequestTrackingjTable.getColumnModel().getColumn(2).setResizable(false);
            RequestTrackingjTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestTrackingjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
