/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analytics;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.OrderQueue.OrderRequest;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohan
 */
public class Time_Lapse extends javax.swing.JPanel {

    /**
     * Creates new form Time_Lapse
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    public Time_Lapse(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business= business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        time_lapsejTable = new javax.swing.JTable();

        jLabel1.setText("Time Lapse from Request to Delivery");

        time_lapsejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Disease", "Vaccine", "Request Date", "Resolve Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(time_lapsejTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable(){
    
    DefaultTableModel model = (DefaultTableModel)time_lapsejTable.getModel();
        
        model.setRowCount(0);int i=0;
        for(CountryNetwork countryNetwork : business.getCountryList()){
            if(countryNetwork.getStateNetwork()!=null){
        for(StateNetwork stateNetwork : countryNetwork.getStateNetwork()){
        if(stateNetwork.getEnterpriseDirectory()!=null){
        for(HospitalEnterprise hospitalEnterprise: stateNetwork.getEnterpriseDirectory().getHospitalEnterprise()){
        if(hospitalEnterprise.getOrganizationDirectory()!=null){
        for(Organization organization: hospitalEnterprise.getOrganizationDirectory().getOrganizationList()){
        if(organization.getUserAccountDirectory()!=null){
        for(UserAccount userAccount: organization.getUserAccountDirectory().getUserAccountList()){
        for(OrderRequest orderRequest : userAccount.getOrderQueue().getOrderRequestList()){
            Object[] row = new Object[5];
            row[0] = orderRequest.getOrderId();
            row[1] = orderRequest.getPatient().getDisease();
            row[2] = orderRequest.getVaccine();
            row[3] = orderRequest.getRequestDate();
            row[4] = orderRequest.getResolveDate();
            
            

            
            model.addRow(row);}
        }
        }
        }
        }
        
        }
        }
        }
        }
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable time_lapsejTable;
    // End of variables declaration//GEN-END:variables
}
